name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore MailTmBlazor/MailTmBlazor.sln

      - name: Build
        run: dotnet build MailTmBlazor/MailTmBlazor.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish MailTmBlazor/MailTmBlazor/MailTmBlazor/MailTmBlazor.csproj --configuration Release --no-build --output published

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: MailTmBlazor
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: published
